version: "3.9"
services:

  sonarqube:
    # default port 9000
    image: sonarqube:lts
    container_name: ce-sonarqube
    restart: unless-stopped
    networks:
      - sonar
    depends_on:
      - database
    environment:
      SONAR_JDBC_URL: ${SONAR_JDBC_URL}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: ce-nginx
    restart: unless-stopped
    networks:
      - sonar
    depends_on:
      - sonarqube
    ports:
      - "8080:80"    # http
      - "8443:443"   # https
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl
      - ${NGINX_LOGS}:/var/log/nginx

  database:
    # default port 5432
    image: postgres:14
    container_name: ce-database
    restart: unless-stopped
    networks:
      - sonar
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data

volumes:
  sonarqube-data:
    name: ce-sonarqube-data
  sonarqube-extensions:
    name: ce-sonarqube-extensions
  sonarqube-logs:
    name: ce-sonarqube-logs
  postgresql:
    name: ce-postgresql
  postgresql-data:
    name: ce-postgresql-data

networks:
  sonar:
    name: ce-sonar
    driver: bridge
