services:
  sonarqube:
    image: sonarqube:community
    container_name: ce-sonarqube
    restart: unless-stopped
    networks:
      - sonar
    depends_on:
      - database
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://database:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs

  nginx:
    image: nginx
    container_name: ce-nginx
    restart: unless-stopped
    networks:
      - sonar
    depends_on:
      - sonarqube
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
      - ./logs/nginx:/var/log/nginx

  database:
    image: postgres:15
    container_name: ce-database
    restart: unless-stopped
    networks:
      - sonar
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data

volumes:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
  postgresql:
  postgresql-data:

networks:
  sonar:
    name: ce-sonar
    driver: bridge
